/*OBS - CLIENT USADO DBEAVER, CLAUSULA DE FECHAMENTO GO EXCLUSIVA NO SERVER MANAGEMENT STUDIO*/


/***************************************************************************/
/**INTRODUÇAO A LINGUAGEM TSQL - É UM BLOCO DE LINGUAGEM DE PROGRAMACAO**/
/*PROGRAMAS SAO UNIDADES QUE PODEM SER CHAMADAS DE BLOCOS ANONIMOS*/
/*BLOCOS ANONIMO NAO RECEBEM NOME POR NAO SEREM SALVOS NO BANCO*/
/*SAO CRIADOS PARA TESTAR ALGO OU EXECUTAR UMA VEZ*/

--CRIANDO UM BLOCO TSQL - BLOCO DE EXECUCAO
BEGIN
	PRINT 'PRIMEIRO BLOCO'
	
END;

/*BLOCO DE ATRIBUICAO DE VARIAVEIS*/
DECLARE
	@CONTADOR INT	
BEGIN
	SET @CONTADOR = 5
	PRINT @CONTADOR
END;

/*NO SQL SERVER CADA COLUNA, VARIAVEL LOCAL, EXPRESSAO E PARAMETRO TEM UM TIPO
  CONCATENACAO E CONVERSAO - CAST É O MAIS UTILIZADO, CONVERT UTILIZADO COM DATAS*/
DECLARE
	@V_NUMERO NUMERIC(10,2) = 100.52,
	@V_DATA DATETIME = '20170207'
BEGIN
	PRINT 'VALOR NUMERICO: ' + CAST(@V_NUMERO AS VARCHAR)
	PRINT 'VALOR NUMERICO: ' + CONVERT(VARCHAR, @V_NUMERO)
	PRINT 'VALOR DE DATA: '  + CAST(@V_DATA AS VARCHAR)
	PRINT 'VALOR DE DATA: '  + CONVERT(VARCHAR, @V_DATA, 121)
	PRINT 'VALOR DE DATA: '  + CONVERT(VARCHAR, @V_DATA, 120)
	PRINT 'VALOR DE DATA: '  + CONVERT(VARCHAR, @V_DATA, 105)
END;


/***************************************************************************/
/**ATRIBUINDO RESULTADO DE QUERY A VARIAVEIS**/
--OBS- V INDICA VARIAVEL E P PARAMETRO

--CRIANDO TABELA
CREATE TABLE CARROS(
	CARRO VARCHAR(20),
	FABRICANTE VARCHAR(30)
);

--INSERINDO DADOS
INSERT INTO CARROS VALUES('KA', 'FORD')
INSERT INTO CARROS VALUES('FIESTA', 'FORD')
INSERT INTO CARROS VALUES('PRISMA', 'FORD')
INSERT INTO CARROS VALUES('CLIO', 'RENAULT')
INSERT INTO CARROS VALUES('SANDERO', 'RENAULT')
INSERT INTO CARROS VALUES('CHEVETE', 'CHEVROLET')
INSERT INTO CARROS VALUES('OMEGA', 'CHEVROLET')
INSERT INTO CARROS VALUES('PALIO', 'FIAT')
INSERT INTO CARROS VALUES('DOBLO', 'FIAT')
INSERT INTO CARROS VALUES('UNO', 'FIAT')
INSERT INTO CARROS VALUES('GOL', 'VOLKSWAGEM');

--DECLARANDO A VARIAVEL
DECLARE  
	@V_CONTADOR_FORD INT,
	@V_CONTADOR_FIAT INT
BEGIN
	--METODO 1 - SELECT RETORNA UMA COLUNA E UM RESULTADO
	SET @V_CONTADOR_FORD = (SELECT COUNT(*) FROM CARROS WHERE FABRICANTE = 'FORD')
	PRINT 'QUANTIDADE FORD: ' + CAST(@V_CONTADOR_FORD AS VARCHAR)
	
	--METODO 2 - VARIAVEL DENTRO DO SELECT
	SELECT @V_CONTADOR_FIAT = COUNT(*) FROM CARROS WHERE FABRICANTE = 'FIAT'
	PRINT 'QUANTIDADE FIAT: ' + CONVERT(VARCHAR, @V_CONTADOR_FIAT)
END;


/***************************************************************************/
/**ESTRUTURAS CONDICIONAIS - IF ELSE**/
/*CADA CASE É UMA COLUNA*/

/*BLOCO DE PROGRAMAÇAO*/
DECLARE
	@NUMERO	INT = 5
BEGIN
	IF @NUMERO = 5
		PRINT 'O VALOR É VERDADEIRO'
	ELSE
		PRINT 'O VALOR É FALSO'
END;


/*FUNÇAO CASE - REPRESENTA UMA COLUNA*/
DECLARE
	@CONTADOR INT
BEGIN
	SELECT
	CASE
		WHEN FABRICANTE = 'FIAT' THEN 'FAIXA 1'
		WHEN FABRICANTE = 'CHEVROLET' THEN 'FAIXA 2'
		ELSE 'OUTRAS FAIXAS'
	END AS "INFORMAÇOES",
	*
	FROM CARROS
END;


/***************************************************************************/
/**ESTRUTURAS DE LOOP COM WHILE**/

/*BLOCO DE PROGRAMAÇAO*/
DECLARE
	@I INT = 1
BEGIN
	WHILE(@I < 15)
	BEGIN
		PRINT 'VALOR DE @I= ' + CAST(@I AS VARCHAR)
		SET @I = @I + 1
	END
END;















