/*OBS - CLIENT USADO DBEAVER, CLAUSULA DE FECHAMENTO GO EXCLUSIVA NO SERVER MANAGEMENT STUDIO*/


/***************************************************************************/
/**PROCEDIMENTOS ARMAZENADOS**/
/*TUDO COMEÇA COM SP_ (STORAGE PROCEDURE)*/
/*FICAM DENTRO DA PASTA PROCEDIMENTOS*/


/*CRIANDO TABELAS*/
CREATE TABLE PESSOA(
	IDPESSOA  INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL CHECK(SEXO IN('M', 'F')),
	NASCIMENTO DATE NOT NULL
);

CREATE TABLE TELEFONE_EMPRESA(
	IDTELEFONE INT NOT NULL IDENTITY,
	TIPO_TELEFONE CHAR(3) NOT NULL CHECK(TIPO_TELEFONE IN('CEL', 'COM')),
	NUMERO_TELEFONE CHAR(10) NOT NULL,
	ID_PESSOA INT
);

/*CRIANDO CHAVE ESTRANGEIRA*/
ALTER TABLE TELEFONE_EMPRESA ADD CONSTRAINT FK_TELEFONE_PESSOA
FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA(IDPESSOA)
ON DELETE CASCADE;

/*INSERINDO DADOS NA TABELA PESSOA*/
INSERT INTO PESSOA VALUES('ANTONIO', 'M', '1981-02-13')
INSERT INTO PESSOA VALUES('DANIEL', 'M', '1985-03-18')
INSERT INTO PESSOA VALUES('CLEIDE', 'F', '1979-10-13');


/*INSERINDO DADOS NA TABELA TELEFONE*/
INSERT INTO TELEFONE_EMPRESA VALUES('CEL', '9879008', 1)
INSERT INTO TELEFONE_EMPRESA VALUES('COM', '8757909', 1)
INSERT INTO TELEFONE_EMPRESA VALUES('CEL', '9875890', 2)
INSERT INTO TELEFONE_EMPRESA VALUES('CEL', '9347689', 2)
INSERT INTO TELEFONE_EMPRESA VALUES('COM', '2998689', 3)
INSERT INTO TELEFONE_EMPRESA VALUES('COM', '2098978', 2)
INSERT INTO TELEFONE_EMPRESA VALUES('CEL', '9008679', 3);


/***************************************************************************/
/**CRIANDO PROCEDURE**/
CREATE PROC SOMA
AS
	SELECT 10 + 10 AS SOMA;


/*EXECUTANDO A PROCEDURE*/
SOMA;

/*OU - MAIS PROFISSIONAL*/
EXEC SOMA;

/*PROCEDURES DINAMICAS - COM PARAMETROS*/
/*O @ DECLARA VARIAVEL OU PARAMETRO*/
/* UM @ INDICA VARIAVEL LOCAL E @@ VARIAVEL GLOBAL*/
CREATE PROC CONTA @NUMERO1 INT, @NUMERO2 INT
AS
	SELECT @NUMERO1 + @NUMERO2 AS RESULTADO;


/*EXECUTANDO A PROCEDURE*/
EXEC CONTA 90,78;

/*APAGANDO A PROCEDURE*/
DROP PROC CONTA;


/***************************************************************************/
/**PROCEDURES EM TABELAS**/
/*PROCEDURES PEDEM PARAMETROS DE ENTRADA E PODEM SAIR COM RESULTADO, PARAMETRO DE SAIDA/OUTPUT*/

/*CONSULTANDO DADOS DA TABELA*/
SELECT P.NOME, T.NUMERO_TELEFONE
FROM PESSOA P
INNER JOIN TELEFONE_EMPRESA T
ON IDPESSOA = ID_PESSOA
WHERE TIPO_TELEFONE = 'CEL';

/*CRIANDO PROCEDURE PARA TRAZER OS NUMEROS DE ACORDO COM O TIPO*/
CREATE PROC TELEFONES @TIPO_TELEFONE CHAR(3)
AS
	SELECT P.NOME, T.NUMERO_TELEFONE
	FROM PESSOA P
	INNER JOIN TELEFONE_EMPRESA T
	ON IDPESSOA = ID_PESSOA
	WHERE TIPO_TELEFONE = @TIPO_TELEFONE;


/*EXECUTANDO A PROCEDURE*/
EXEC TELEFONES 'CEL';
EXEC TELEFONES 'COM';

/*PROCEDIMENTOS DE OUTPUT*/
SELECT TIPO_TELEFONE, COUNT(*) AS QUANTIDADE
FROM TELEFONE_EMPRESA 
GROUP BY TIPO_TELEFONE;

/*CRIANDO A PROCEDURE APROVEITANDO A QUERY - PARAMETRO DE ENTRADA E SAIDA*/
CREATE PROCEDURE GET_TIPO @TIPO_TELEFONE CHAR(3), @CONTADOR INT OUTPUT
AS
	SELECT @CONTADOR = COUNT(*)
	FROM TELEFONE_EMPRESA 
	WHERE TIPO_TELEFONE = @TIPO_TELEFONE;


/*EXECUÇAO DA PROCEDURE COM PARAMETRO DE SAIDA*/
/*TRANSACTIONAL SQL - LINGUAGEM QUE O SQL SERVER TRABALHA*/
DECLARE @SAIDA INT
EXEC GET_TIPO @TIPO_TELEFONE = 'CEL', @CONTADOR = @SAIDA OUTPUT
SELECT @SAIDA;


/*OUTRA FORMA*/
DECLARE @SAIDA INT
EXEC GET_TIPO 'CEL', @SAIDA OUTPUT
SELECT @SAIDA;


/***************************************************************************/
/**CRIANDO PROCEDURES COMO REGRA DE NEGOCIO**/
/*OS DADOS ENTRAM PELA CAMADA VIEW E TEM SEU PROCESSAMENTO E ARMAZENAMENTO NO BANCO*/
/*VAI SER FEITA UMA ENTRADA DE DADOS EM DUAS TABELAS AO MESMO TEMPO*/
/*PROCEDIMENTO FEITO POR MEIO DE REGRAS NO PROCEDURE*/

/*PROCEDURE DE CADASTRO*/
CREATE PROC CADASTRO @NOME VARCHAR(30), @SEXO CHAR(1), @NASCIMENTO DATE,
@TIPO_TELEFONE CHAR(3), @NUMERO_TELEFONE VARCHAR (10)
AS 
	DECLARE @FK INT
	
	INSERT INTO PESSOA VALUES (@NOME, @SEXO,  @NASCIMENTO)

	SET @FK = (SELECT IDPESSOA FROM PESSOA WHERE IDPESSOA = @@IDENTITY)
	
	INSERT INTO TELEFONE_EMPRESA VALUES (@TIPO_TELEFONE, @NUMERO_TELEFONE, @FK);


/*EXECUTANDO A PROCEDURE INSERINDO EM DUAS TABELAS AO MESMO TEMPO*/
CADASTRO 'JORGE', 'M', '1981-01-01', 'CEL', '97273822';


/*CONSULTANDO OS DADOS INSERIDOS*/
/*FORMA ABREVIADA*/
SELECT PESSOA.*, TELEFONE_EMPRESA.*
FROM PESSOA
INNER JOIN TELEFONE_EMPRESA 
ON IDPESSOA = ID_PESSOA;

































