/*OBS - CLIENT USADO DBEAVER, CLAUSULA DE FECHAMENTO GO EXCLUSIVA NO SERVER MANAGEMENT STUDIO*/

/* ORGANIZAR FISICAMENTE E LOGICAMENTE UM BANCO DE DADOS.

1- CRIAR UM BANCO COM ARQUIVOS PARA OS SETORES DE MARQUETING E VENDAS.

2- CRIAR UM ARQUIVO GERAL, QUEM NAO SE ENQUADRAR NO ITEM ANTERIOR FICA SEPARADO.

3- DEIXAR O MDF APENAS COM  O DICIONARIO DE DADOS.

4- CRIAR DOIS GRUPOS DE ARQUIVOS (PRIMARY - MDF). */	


/*Mostrar local onde arquivo MDF está sendo salvo, diretório do arquivo*/
SELECT name, physical_name, state, database_id FROM sys.master_files;

/*Comando para parar o banco de dados*/
ALTER DATABASE nomeDoBanco SET OFFLINE;


